---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: armbian-bookworm-edge-x86-efi
spec:
  running: false # this defines the VM as stopped, you need to start it manually with virtctl
  template:
    metadata:
      labels:
        kubevirt.io/vm: armbian-bookworm-edge-x86-efi
        app.kubernetes.io/name: VM_armbian-bookworm-edge-x86-efi # For Hubble & others
    spec:
      architecture: amd64
      nodeSelector:
        kubernetes.io/arch: amd64
      domain:
        # machine.type not specified, defaults to q35
        chassis:
          serial: pardini-chassis-serial
          asset: pardini-chassis-asset
          sku: pardini-chassis-sku
          version: pardini-chassis-version
          manufacturer: "pardini-chassis-manufacturer"
        
        firmware:
          # UEFI: boots grub which defines cmdline, kernel & initrd # 
          bootloader:
            efi:
              secureBoot: false
        
        cpu:
          cores: 4
        devices:
          autoattachGraphicsDevice: false # no graphics, thanks
          disks:
            - disk:
                bus: virtio
              name: containerdisk
              serial: containerdiskserial
            - disk:
                bus: virtio
              name: cloudinitdisk
              serial: cloudinitdiskserial
            - name: emptydisk
              serial: emptydiskserial
              disk:
                bus: virtio
            #- disk:
            #    bus: virtio
            #  name: host-disk
            #  serial: host-disk-serial
          interfaces:
            - masquerade: { }
              name: default
          rng: { } # source of randomness
        resources:
          requests:
            memory: 4G
      networks:
        - name: default
          pod: { }
      terminationGracePeriodSeconds: 0
      volumes:
        - containerDisk: # this is an OCI image that has a disk/xxx.qcow2 inside. it is ephemeral, but rw
            image: ghcr.io/rpardini/armbian-cloud-container-disk:bookworm-edge-latest
            imagePullPolicy: Always # Since we're using a "latest" above, we need to force a pull every time.
          name: containerdisk

        - cloudInitNoCloud: # auto create .ISOs for us, thanks.
            userData: |-
              #include https://cloud-init.pardini.net/rpardini/oldskool-rpardini/master/armbian_kubevirt_amd64
          name: cloudinitdisk

        - name: emptydisk # throwaway disk, for testing. does not persist.
          emptyDisk:
            capacity: 2Gi

        #- hostDisk: # persistent disk, using a file directly on the k8s host running this VM. Similar to hostPath, but with a .img wrapper.
        #    capacity: 3Gi
        #    path: /var/lib/opensearch/kubevirt-hostdisk-fedora.img
        #    type: DiskOrCreate
        #  name: host-disk
