name: armbian-bookworm-edge
on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - 'containerDisk-armbian.sh'
      - '.github/workflows/armbian-bookworm-edge.yml'
jobs:
  armbian-bookworm:
    
    permissions:
      packages: write
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout build repo
        uses: actions/checkout@v4

      - name: Docker Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }} # GitHub username or org
          password: ${{ secrets.GITHUB_TOKEN }}    # GitHub actions builtin token. repo has to have pkg access.

      - name: Install deps
        id: deps
        run: |
          sudo --preserve-env apt update
          sudo --preserve-env apt install -y curl jq pixz

      - name: Run magic script
        id: magic
        env:
          DISK_OCI_REF: "ghcr.io/${{ github.repository_owner }}/armbian-cloud-container-disk"
          KERNEL_OCI_REF: "ghcr.io/${{ github.repository_owner }}/armbian-cloud-kernel-kv"
          RELEASE: "bookworm"
          BRANCH: "edge"
        run: |
          sudo --preserve-env bash containerDisk-armbian.sh
